### ISSUE TITLE
[Security] Workflow linter.yml is using vulnerable action reviewdog/action-eslint

### ISSUE THREAD

**Issue by akulpillai** [kennethlmartin/react-next-template#3]
The workflow linter.yml is referencing action reviewdog/action-eslint using references v1. However this reference is missing the commit [7b45345d875d4979afe88b630dbc01a40e8a2e91](https://github.com/reviewdog/action-eslint/commits/7b45345d875d4979afe88b630dbc01a40e8a2e91) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by kennethlmartin** [comment]
Thanks for the update! It does appear that the maintainer of the action has since created a release that includes this update. There is no need to reference a more precise SHA or minor/patch tagged version because we will always use the latest v1 release.
